routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*
Route::get('/welcome', function () {
    return view('welcome');
});*/

Auth::routes();

Route::get('/','App\Http\Controllers\BlogController@index')->name('index');
Route::get('entrada/{id}','App\Http\Controllers\BlogController@entrada')->name('entrada');

Route::group(['prefix' => 'administrador', 'middleware' => 'auth'], function () {
    Route::resource('entradas', 'App\Http\Controllers\EntradasController');
    Route::resource('comentarios', 'App\Http\Controllers\ComentariosController');

});

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Entradas;
use App\Models\Comentarios;

class BlogController extends Controller
{
    public function index()
    {	
    	$entradas = Entradas::orderBy('entradas.id','DESC')->select('entradas.id as entradas_id','users.id as users_id', 'users.name','entradas.titulo','entradas.contenido','entradas.created_at')->join('users', 'users.id', '=', 'entradas.autor_id')->paginate(5);
    	return view('blog.index', compact('entradas'));
    }

    public function entrada($id)
    {
    	$entrada = Entradas::where('entradas.id', $id)->select('entradas.id as entradas_id','users.id as users_id', 'users.name','entradas.titulo','entradas.contenido','entradas.created_at')->join('users', 'users.id', '=', 'entradas.autor_id')->first();
        $comentarios = Comentarios::where('comentarios.entradas_id', $id)->select('comentarios.id as comentarios_id','users.id as users_id', 'users.name','comentarios.comentario','comentarios.created_at')->join('users', 'users.id', '=', 'comentarios.autor_id')->get();

    	//if($entrada){
    		return view('blog.entrada', compact('entrada','comentarios'));
    	//}
    	/*else{
    		return \Response::view('blog.errors.404', array(), 404);
    	}*/
    	
    }
}

resources/views/blog/template/master.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Blog - Julio Delgado</title>

  <!-- Bootstrap core CSS -->
  <link href="{{ asset('website/vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="{{ asset('website/vendor/fontawesome-free/css/all.min.css') }}" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

  <!-- Custom styles for this template -->
  <link href="{{ asset('website/css/clean-blog.min.css') }}" rel="stylesheet">

  <style>
        .page-link {
            color: #00657b;
            text-align: center;
        }
        .page-item.active .page-link {
            background-color: #00657b;
            border-color: #00657b;
        }
        .shadow-sm{
          display: none;
        }
    </style>

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand" href="{{ url('/') }}">INICIO</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{{ route('entradas.index') }}">Entradas</a>
          </li>
          @if (Auth::check())
          <li class="nav-item">
            <a class="nav-link" href="{{ route('logout') }}" onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();"
                                        >Salir</a>
            <form id="logout-form" action="{{ route('logout') }}" method="POST"
                                          style="display: none;">
                                        @csrf
                                    </form>
          </li>
          @endif
          @if (!Auth::check())
          <li class="nav-item">
            <a class="nav-link" href="{{ route('register') }}">Registro</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
          </li>
          @endif
        </ul>
      </div>
    </div>
  </nav>

  @yield('content')

  <hr>

  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <ul class="list-inline text-center">
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          </ul>
          <p class="copyright text-muted">Copyright &copy; Your Website 2020</p>
        </div>
      </div>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{{ asset('website/vendor/jquery/jquery.min.js') }}"></script>
  <script src="{{ asset('website/vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>

  <!-- Custom scripts for this template -->
  <script src="{{ asset('website/js/clean-blog.min.js') }}"></script>

</body>

</html>